# Generated by Django 5.2.8 on 2025-11-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rider_mongo_user_id_alter_rider_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='mongo_user_Id',
            new_name='mongo_user_id',
        ),
    ]
