# Generated by Django 5.2.8 on 2025-11-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_rename_mongo_user_id_rider_mongo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='mongo_user_id',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropOffStr',
            field=models.CharField(default='Drop Up Loc', max_length=20),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickupStr',
            field=models.CharField(default='Pick Up Loc', max_length=20),
        ),
    ]
