# Generated by Django 4.2.26 on 2025-12-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_remove_rider_mongo_user_id_riderequest_dropoffstr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rider",
            name="location",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="user",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="dropoff",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="pickup",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="rider",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Rider",
        ),
        migrations.DeleteModel(
            name="RideRequest",
        ),
    ]
